# Read about factories at https://github.com/thoughtbot/factory_girl

FactoryGirl.define do
  factory :raw_tweet do
    raw '{\"created_at\":\"Mon Jul 07 12:17:15 +0000 2014\",\"id\":486121764615778304,\"id_str\":\"486121764615778304\",\"text\":\"@AFL @AFLPlayers The best game on Earth with the worst half time show on grand final day. Book someone now #letmeknowifuwantideas\",\"source\":\"\\u003ca href=\\\"http://twitter.com/download/iphone\\\" rel=\\\"nofollow\\\"\\u003eTwitter for iPhone\\u003c/a\\u003e\",\"truncated\":false,\"in_reply_to_status_id\":null,\"in_reply_to_status_id_str\":null,\"in_reply_to_user_id\":16319888,\"in_reply_to_user_id_str\":\"16319888\",\"in_reply_to_screen_name\":\"AFL\",\"user\":{\"id\":297245835,\"id_str\":\"297245835\",\"name\":\"Mick Reed\",\"screen_name\":\"mickreed79\",\"location\":\"\",\"url\":null,\"description\":null,\"protected\":false,\"followers_count\":18,\"friends_count\":88,\"listed_count\":0,\"created_at\":\"Thu May 12 05:49:37 +0000 2011\",\"favourites_count\":34,\"utc_offset\":null,\"time_zone\":null,\"geo_enabled\":false,\"verified\":false,\"statuses_count\":101,\"lang\":\"en\",\"contributors_enabled\":false,\"is_translator\":false,\"is_translation_enabled\":false,\"profile_background_color\":\"C0DEED\",\"profile_background_image_url\":\"http://abs.twimg.com/images/themes/theme1/bg.png\",\"profile_background_image_url_https\":\"https://abs.twimg.com/images/themes/theme1/bg.png\",\"profile_background_tile\":false,\"profile_image_url\":\"http://pbs.twimg.com/profile_images/1577639942/image_normal.jpg\",\"profile_image_url_https\":\"https://pbs.twimg.com/profile_images/1577639942/image_normal.jpg\",\"profile_link_color\":\"0084B4\",\"profile_sidebar_border_color\":\"C0DEED\",\"profile_sidebar_fill_color\":\"DDEEF6\",\"profile_text_color\":\"333333\",\"profile_use_background_image\":true,\"default_profile\":true,\"default_profile_image\":false,\"following\":null,\"follow_request_sent\":null,\"notifications\":null},\"geo\":null,\"coordinates\":null,\"place\":null,\"contributors\":null,\"retweet_count\":0,\"favorite_count\":0,\"entities\":{\"hashtags\":[{\"text\":\"letmeknowifuwantideas\",\"indices\":[107,129]}],\"symbols\":[],\"urls\":[],\"user_mentions\":[{\"screen_name\":\"AFL\",\"name\":\"AFL\",\"id\":16319888,\"id_str\":\"16319888\",\"indices\":[0,4]},{\"screen_name\":\"AFLPlayers\",\"name\":\"AFL Players\",\"id\":41718791,\"id_str\":\"41718791\",\"indices\":[5,16]}]},\"favorited\":false,\"retweeted\":false,\"filter_level\":\"medium\",\"lang\":\"en\"}'
    tweet_guid 486121764615778304
  end

  factory :raw_tweet_with_invalid_json, parent: :raw_tweet do |f|
    f.raw '\"created_at\":\"Mon Jul 07 12:17:15 +0000 2014\",\"id\":486121764615778304,\"id_str\":\"486121764615778304\",\"text\":\"@AFL @AFLPlayers The best game on Earth with the worst half time show on grand final day. Book someone now #letmeknowifuwantideas\",\"source\":\"\\u003ca href=\\\"http://twitter.com/download/iphone\\\" rel=\\\"nofollow\\\"\\u003eTwitter for iPhone\\u003c/a\\u003e\",\"truncated\":false,\"in_reply_to_status_id\":null,\"in_reply_to_status_id_str\":null,\"in_reply_to_user_id\":16319888,\"in_reply_to_user_id_str\":\"16319888\",\"in_reply_to_screen_name\":\"AFL\",\"user\":{\"id\":297245835,\"id_str\":\"297245835\",\"name\":\"Mick Reed\",\"screen_name\":\"mickreed79\",\"location\":\"\",\"url\":null,\"description\":null,\"protected\":false,\"followers_count\":18,\"friends_count\":88,\"listed_count\":0,\"created_at\":\"Thu May 12 05:49:37 +0000 2011\",\"favourites_count\":34,\"utc_offset\":null,\"time_zone\":null,\"geo_enabled\":false,\"verified\":false,\"statuses_count\":101,\"lang\":\"en\",\"contributors_enabled\":false,\"is_translator\":false,\"is_translation_enabled\":false,\"profile_background_color\":\"C0DEED\",\"profile_background_image_url\":\"http://abs.twimg.com/images/themes/theme1/bg.png\",\"profile_background_image_url_https\":\"https://abs.twimg.com/images/themes/theme1/bg.png\",\"profile_background_tile\":false,\"profile_image_url\":\"http://pbs.twimg.com/profile_images/1577639942/image_normal.jpg\",\"profile_image_url_https\":\"https://pbs.twimg.com/profile_images/1577639942/image_normal.jpg\",\"profile_link_color\":\"0084B4\",\"profile_sidebar_border_color\":\"C0DEED\",\"profile_sidebar_fill_color\":\"DDEEF6\",\"profile_text_color\":\"333333\",\"profile_use_background_image\":true,\"default_profile\":true,\"default_profile_image\":false,\"following\":null,\"follow_request_sent\":null,\"notifications\":null},\"geo\":null,\"coordinates\":null,\"place\":null,\"contributors\":null,\"retweet_count\":0,\"favorite_count\":0,\"entities\":{\"hashtags\":[{\"text\":\"letmeknowifuwantideas\",\"indices\":[107,129]}],\"symbols\":[],\"urls\":[],\"user_mentions\":[{\"screen_name\":\"AFL\",\"name\":\"AFL\",\"id\":16319888,\"id_str\":\"16319888\",\"indices\":[0,4]},{\"screen_name\":\"AFLPlayers\",\"name\":\"AFL Players\",\"id\":41718791,\"id_str\":\"41718791\",\"indices\":[5,16]}]},\"favorited\":false,\"retweeted\":false,\"filter_level\":\"medium\",\"lang\":\"en\"}'
  end

end